language: python
python: 2.7
env:
 - TOXENV=py34
 - TOXENV=py36
 - TOXENV=py27
install:
 - pip install tox
 - pip install codecov
script:
 - tox
after_success:
 - codecov -t b23f9815-6e51-449b-92c2-11521da6d24a
